### ISSUE TITLE
Update Node.js version

### ISSUE THREAD

**Issue by zachsa** [ASzc/change-string-case-action#7]
Hi,

Thank you for the open source, and useful GitHub action! Recently a warning has started appearing in the console:

>Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/20***-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Would it be possible/easy to update the action to address the deprecation message?

**Comment by ASzc** [comment]
Fixed in v3

**Comment by zachsa** [comment]
Thank you very much

**Comment by vishalmamidi** [comment]
Hello @ASzc 

I am using latest version v4 and still getting warnings.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/12382861/198707558-2467b548-b700-4975-a45f-848368614884.png">

**Comment by ASzc** [comment]
I'm not sure why that is. I don't think this would be a regression in v4 vs v3.

The fix depends on the version of `@actions/core` in use. Github's blog post promises v1.10.0 or greater will use the correct implementation of the `setOutput` function. This action's package.json and package-lock.json both specify `^1.10.0` now, which will accept version `1.10.0` and later versions within `1.x`.

I'm not sure how the internals of Github Actions work at runtime, but it seems possible to me that the workflow, or maybe another action could specify something that causes an old version of core to be loaded? Is this issue still fixed for you @zachsa?

**Comment by zachsa** [comment]
I haven't bumped the version yet. I'll do so on Monday and confirm

**Comment by Olzie-12** [comment]
having this issue as well

**Comment by zachsa** [comment]
I'm also still getting the warnings for v4

**Comment by Olzie-12** [comment]
I just used bash commands as an alternative

**Comment by ASzc** [comment]
I have no idea why this isn't working. I checked what a few other actions did to solve this, and it's exactly the same thing I applied here

**Comment by ASzc** [comment]
Try v5 please. The only difference I could find was these other projects didn't have a commited node_modules directory

**Comment by ZackaryWelch** [comment]
Seeing errors from v5 about the @actions/core dependencies. A disucssion elsewhere mentioned committing node_modules.

**Comment by ASzc** [comment]
Ah! Ok, I've updated the v5 release to still contain node_modules, but with a fresh `npm -i` applied to it.

Thanks for everyone's patience with my unprofessional handling of this issue. I made this action on a while back and I don't have anywhere to test it anymore
